### ISSUE TITLE
Plase add botton to send BLOR command

### ISSUE THREAD

**Issue by skoblov** [khenderick/esphome-opentherm#14]
BAXI bowlers neet BLOR comand to reset an error

Now I use template button with lambda, but it need to remove private: section from your header. It's better to include this button to component

  - platform: template
    name: "BLOR"
    icon: "mdi:lock-reset"
    on_press:
      lambda: |-
        opentherm_openthermcomponent->request_(opentherm::OpenThermMessageType::WRITE_DATA, opentherm::OpenThermMessageID::COMMAND, 0x100);

**Comment by khenderick** [comment]
I've quickly added button for the two commands currently defined in the spec. However, I'm currently unable to test them out myself, can you give them a try and let me know whether they work?

You can test the new functionality by updating your configuration:

```
...

external_components:
  source: github://khenderick/esphome-opentherm@commands
  components: [opentherm]
  refresh: 0s

...

button:
  - platform: opentherm
    boiler_lo_reset:
      name: "Boiler lock-out reset"
    ch_water_filling:
      name: "CH water filling"
...
```
