### ISSUE TITLE
Default ch, dhw and otc enabled switches to enabled

### ISSUE THREAD

**Issue by aelking** [khenderick/esphome-opentherm#20]
I have tried to use

restore_mode: ALWAYS_ON
on
ch_enabled
dhwenabled
otc_active

but it doesn't seem to do anything.

```
switch:
  - platform: opentherm
    ch_enabled:
      name: "CH enabled"
      restore_mode: ALWAYS_ON
    dhw_enabled:
      name: "DHW enabled"
      restore_mode: ALWAYS_ON
    otc_active:
      name: "OTC active"
      restore_mode: ALWAYS_ON
```

Is this something that I am doing wrong, or is it something that needs to be implented?
