### ISSUE TITLE
add enable OTC

### ISSUE THREAD

**Issue by ananyevgv** [khenderick/esphome-opentherm#9]
MessageID::Status enableOutsideTemperatureCompensation << 3

**Comment by ananyevgv** [comment]
HB: Slave configuration flag8 bit: description [ clear/0, set/1]
0: DHW present [ dhw not present, dhw is present ]
1: Control type [ modulating, on/off ]
2: Cooling config [ cooling not supported,
cooling supported]
3: DHW config [instantaneous or not-specified,
storage tank]
4: Master low-off&pump control function [allowed,
not allowed]
5: CH2 present [CH2 not present, CH2 present]

**Comment by ananyevgv** [comment]
![image](https://github.com/khenderick/esphome-opentherm/assets/81970899/c2382602-2634-42ae-b355-2c81377498cd)

**Comment by khenderick** [comment]
> MessageID::Status enableOutsideTemperatureCompensation << 3

Implementation on its way :+1: 

> HB: Slave configuration flag8 bit

Would this make sense if implemented using binary sensors? Especially `DHW config` is a tricky one, since I'd have to name this differently like `dhw_storage_tank` so `true` means that there is a storage tank and `false` means it's instantaneous or not-specified.

> _(screenshot)_

Implementation on its way :+1:

**Comment by khenderick** [comment]
I've pushed a branch with the new sensors. Can you give them a try and keep me posted if they work as expected?

```
...

external_components:
  source: github://khenderick/esphome-opentherm@extra
  components: [opentherm]
  refresh: 0s

...

sensor:
  - platform: opentherm
    ...
    dhw_2_temperature:
      name: "DHW 2 temperature"
    exhaust_temperature:
      name: "exhaust temperature"
    burner_starts:
      name: "burner starts"
    burner_ops_hours:
      name: "burner operation hours"
    ch_pump_starts:
      name: "CH pump starts"
    ch_pump_ops_hours:
      name: "CH pump operation hours"
    dhw_pump_valve_starts:
      name: "DHW pump/valve starts"
    dhw_pump_valve_ops_hours:
      name: "DHW pump/valve operation hours"
    dhw_burner_starts:
      name: "DHW burner starts"
    dhw_burner_ops_hours:
      name: "DHW burner operation hours"
    ...

...

switch:
  - platform: opentherm
    ...
    otc_active:
      name: "OTC active"
    ...

...
```
